# aws cloudformation delete-stack --stack-name scikit-image
# aws cloudformation create-stack --stack-name scikit-image --template-body file://build-image.yml

Description: Create a CodePipeline for creating a Docker base image for training/serving models
Parameters:
  CodeRepoName:
    Type: String
    Description: Name of the CodeCommit repo
  CodeBranchName:
    Type: String
    Description: Name of the branch the code is located
  ImageRepoName:
    Type: String
    Description: Name of the ECR repo without the image name
  ImageTagName:
    Type: String
    Description: Name of the ECR image tag
    Default: latest
  BaseRepoName:
    Type: String
    Description: Optional Name of the ECR repo without the image name is based on
  ArtifactBucket:
    Type: String
    Description: The bucket for pipeline artifacts
  MLOpsRoleArn:
    Type: String
    Description: Role for CodeBuild and CodePipeline 
  
Resources:

  BuildImageProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-buildimage
      Description: Build a Model Image
      ServiceRole: !Ref MLOpsRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:17.09.0
        EnvironmentVariables:
          - Name: BASE_REPO_NAME
            Value: !Ref BaseRepoName
          - Name: IMAGE_REPO_NAME
            Value: !Ref ImageRepoName
          - Name: IMAGE_TAG
            Value: !Ref ImageTagName
          - Name: AWS_ACCOUNT_ID
            Value: !Sub ${AWS::AccountId}
          - Name: AWS_DEFAULT_REGION
            Value: !Sub ${AWS::Region}
          - Name: TEMPLATE_BUCKET
            Value: !Ref ArtifactBucket
          - Name: TEMPLATE_PREFIX
            Value: codebuild
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-buildimage

  DeployPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Sub ${AWS::StackName}
      RoleArn: !Ref MLOpsRoleArn
      ArtifactStore:
          Type: S3
          Location: !Ref ArtifactBucket
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: GetSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                -
                  Name: ModelSourceOutput
              Configuration:
                BranchName: 
                  Ref: CodeBranchName
                RepositoryName: 
                  Ref: CodeRepoName
              RunOrder: 1
        -
          Name: Build
          Actions:
            -
              Name: BuildImage
              InputArtifacts:
                - Name: ModelSourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                  ProjectName:
                    Ref: BuildImageProject
              RunOrder: 1
  
