Description: Template for sagemaker custom resources
Transform: AWS::Serverless-2016-10-31
Resources:
  MonitoringScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-cfn-monitoring-schedule
      CodeUri: ../cfn
      Handler: sagemaker_monitoring_schedule.lambda_handler
      Runtime: python3.7
      Role: !GetAtt SagemakerCustomResourceRole.Arn

  EnableDataCaptureFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-cfn-enable-data-capture
      CodeUri: ../cfn
      Handler: sagemaker_data_capture.lambda_handler
      Runtime: python3.7
      Role: !GetAtt SagemakerCustomResourceRole.Arn

  TrainingWaiterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mlops-cfn-training-job-waiter
      CodeUri: ../cfn
      Handler: sagemaker_training_waiter.lambda_handler
      Runtime: python3.7
      Role: !GetAtt SagemakerCustomResourceRole.Arn
      
  SagemakerCustomResourceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: mlops-cfn-sagemaker-custom-resource
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyDocument:
            Statement:
              - 
                Sid: AllowSageMaker
                Effect: Allow
                Action:
                  - sagemaker:DescribeTrainingJob
                  - sagemaker:DescribeEndpoint
                  - sagemaker:UpdateEndpoint
                  - sagemaker:CreateEndpointConfig
                  - sagemaker:DescribeEndpointConfig
                  - sagemaker:DeleteEndpointConfig
                  - sagemaker:CreateMonitoringSchedule
                  - sagemaker:DeleteMonitoringSchedule
                  - sagemaker:DescribeMonitoringSchedule
                Resource: "arn:aws:sagemaker:*:*:*/*"
              - 
                Sid: AllowLambda
                Effect: Allow
                Action:
                - lambda:* # Requires at least lambda:AddPermission
                Resource: "*" # TODO: Narrow this down 
              - 
                Sid: AllowEvents
                Effect: Allow
                Action:
                - events:* # Requires at least events:PutRule/events:RemoveTargets
                Resource: "*" # TODO: Narrow this down
              - 
                Sid: AllowPassRole
                Effect: Allow
                Action:
                 - iam:PassRole
                Resource: "*"
                Condition:
                  StringEquals:
                    iam:PassedToService: sagemaker.amazonaws.com
            Version: '2012-10-17'
          PolicyName: SagemakerCustomResource