AWSTemplateFormatVersion: '2010-09-09'
Description: 'Machine Learning Ops Workshop with SageMaker: lab guides and materials'
Parameters:
  BaseRepoName:
    Type: String
    Description: Name of the ECR repo / branch for base image
    Default: ludwig-text
    MinLength: 1
    MaxLength: 24
    AllowedPattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
  ImageRepoName:
    Type: String
    Description: Name of the ECR repo / branch for model image
    Default: ludwig-bank
    MinLength: 1
    MaxLength: 24
    AllowedPattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
  ImageTagName:
    Type: String
    Description: Name of the ECR repo / branch for model image
    Default: latest
    MinLength: 1
    MaxLength: 24
    AllowedPattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
  ModelName:
    Type: String
    Description: Name of the model
    Default: banking
    MinLength: 1
    MaxLength: 24
    AllowedPattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
  NotebookInstanceType:
    Type: String
    Default: ml.t3.medium
    AllowedValues:
      - ml.t3.medium
      - ml.t3.large
      - ml.t3.2xlarge
      - ml.m5.large
      - ml.m5.xlarge
      - ml.m5.2xlarge
    Description: Enter ml instance size for notebook. Default is t2.micro.
  DatasetBucket:
    Type: String
    Description: The source dataset bucket
    Default: open-banking-classificaiton-ap-southeast-2
    MinLength: 1
    MaxLength: 24
    AllowedPattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
  DatasetPrefix:
    Type: String
    Description: The s3 data source which should contain '/train/' and '/validation/' keys
    Default: data/
    MinLength: 1
    MaxLength: 24
    AllowedPattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*

Resources:
  MLOpsBaseImageRepo:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref BaseRepoName

  MLOpsModelRepo:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref ImageRepoName

  MLOpsBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub mlops-${AWS::Region}-${AWS::AccountId}
      Tags:
        - Key: Name
          Value: !Sub mlops-${AWS::Region}-${AWS::AccountId}
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

  MLOpsRepo:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: Repository for the ML models/images code
      RepositoryName: !Ref ModelName
      
  IAWorkshopNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      NotebookInstanceName: amazon-sagemaker-mlops
      InstanceType: !Ref NotebookInstanceType
      RoleArn: !GetAtt MLOps.Arn
      LifecycleConfigName: !GetAtt IAWorkshopNotebookInstanceLifecycleConfig.NotebookInstanceLifecycleConfigName
    DependsOn: 
      - IAWorkshopNotebookInstanceLifecycleConfig
      - MLOps
      - MLOpsBucket
      - MLOpsRepo

  IAWorkshopNotebookInstanceLifecycleConfig:
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties:
      NotebookInstanceLifecycleConfigName: !Sub ${AWS::StackName}-lifecycle-config
      OnStart:
        - Content: 
            Fn::Base64:
              Fn::Sub: |
                #!/bin/bash

                # set some ENV vars for the BASE_REPO, IMAGE_REPO and MODEL_NAME
                touch /etc/profile.d/jupyter-env.sh
                echo "export REGION=${AWS::Region}" >> /etc/profile.d/jupyter-env.sh
                echo "export BASE_REPO=${BaseRepoName}" >> /etc/profile.d/jupyter-env.sh
                echo "export IMAGE_REPO=${ImageRepoName}" >> /etc/profile.d/jupyter-env.sh
                echo "export IMAGE_TAG=${ImageTagName}" >> /etc/profile.d/jupyter-env.sh
                echo "export MODEL_NAME=${ModelName}" >> /etc/profile.d/jupyter-env.sh
                echo "export DATASET_BUCKET=${DatasetBucket}" >> /etc/profile.d/jupyter-env.sh
                echo "export DATASET_PREFIX=${DatasetPrefix}" >> /etc/profile.d/jupyter-env.sh
                initctl restart jupyter-server --no-wait

                echo "Configuring github for AWS credentials"
                git config --global credential.helper '!aws codecommit credential-helper $@'
                git config --global credential.UseHttpPath true
                
                cp /root/.gitconfig /home/ec2-user/ && chown ec2-user:ec2-user /home/ec2-user/.gitconfig

                echo "Now let's prepare our code commit repo"
                git clone https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${ModelName} /tmp/mlops-temp

                echo "First the master branch"
                cd /tmp/mlops-temp
                printf "version: 0.2\nphases:\n  build:\n    commands:\n      - echo 'dummy'\n" > buildspec.yml
                git add buildspec.yml
                git commit -a -m ' - repo init'
                git push

                echo "Then the base branch"
                git checkout -b ${BaseRepoName}
                git push --set-upstream origin ${BaseRepoName}
                
                echo "Then our image model branch"
                git checkout -b ${ImageRepoName}
                git push --set-upstream origin ${ImageRepoName}

                cd ../
                rm -rf /tmp/mlops-temp

                echo "Downloading exercises..."
                git clone -b prd-api https://github.com/brightsparc/amazon-sagemaker-mlops-workshop.git /home/ec2-user/SageMaker/mlops-workshop

                echo "Now let's clone both branches we just created"
                mkdir -p /home/ec2-user/SageMaker/mlops-workshop-images
                git clone --single-branch -b ${BaseRepoName} https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${ModelName}  /home/ec2-user/SageMaker/mlops-workshop-images/${BaseRepoName}
                git clone --single-branch -b ${ImageRepoName} https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${ModelName}  /home/ec2-user/SageMaker/mlops-workshop-images/${ImageRepoName}
                git clone --single-branch -b master https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${ModelName}  /home/ec2-user/SageMaker/mlops-workshop-images/master

                echo "Finally, let's clone and build an image for testing codebuild locally"
                git clone https://github.com/aws/aws-codebuild-docker-images.git /tmp/aws-codebuild
                chmod +x /tmp/aws-codebuild/local_builds/codebuild_build.sh

                docker pull amazon/aws-codebuild-local:latest --disable-content-trust=false

                chown ec2-user:ec2-user -R /home/ec2-user/SageMaker/

                cd /home/ec2-user/SageMaker/mlops-workshop

                echo "Install custom resource helper, and create the sagemaker custom resource stack"

                pip install -t ./cfn crhelper

                aws cloudformation create-stack --stack-name sagemaker-custom-resource \
                --template-body file://assets/sagemaker-custom-resource.yml \

                parameters="ParameterKey=ModelName,ParameterValue=${ModelName}"
                parameters="$parameters ParameterKey=RepoBranchName,ParameterValue=%"
                parameters="$parameters ParameterKey=ImageRepoName,ParameterValue=%s"
                parameters="$parameters ParameterKey=ImageTagName,ParameterValue=${ImageTagName}"

                echo "Create code pipeline repos for image build and train model"

                aws cloudformation create-stack --stack-name mlops-repo-${BaseRepoName} \
                  --template-body file://assets/build-image.yml \
                  --parameters $(printf "$parameters" "${BaseRepoName}" "${BaseRepoName}" )

                aws cloudformation create-stack --stack-name mlops-repo-${ImageRepoName} \
                  --template-body file://assets/build-image.yml \
                  --parameters $(printf "$parameters" "${ImageRepoName}" "${ImageRepoName}" )

                aws cloudformation create-stack --stack-name mlops-pipeline-${ModelName} \
                  --template-body file://assets/train-model-pipeline.yml \
                  --parameters $(printf "$parameters" "master" "${ImageRepoName}" )
                
                echo "Done! Let's do some stuff with this env"

  MLOpsCodeBuild:
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: MLOpsCodeBuild
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codebuild.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "Admin"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"

  MLOps:
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: MLOps
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "sagemaker.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "cloudformation.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codepipeline.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codebuild.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "events.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "Admin"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"